"""add label to role

Revision ID: b0e2b55721bd
Revises: 9429d9e2ef7f
Create Date: 2020-05-28 16:10:09.454301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b0e2b55721bd'
down_revision = '9429d9e2ef7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role_translation', sa.Column('label', sa.Unicode(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('role_translation', 'label')
