"""Auth type

Revision ID: e793fb176cbf
Revises: 1fba1a39c681
Create Date: 2020-03-13 23:04:08.982458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e793fb176cbf'
down_revision = '1fba1a39c681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('authentication_type', sa.Enum('LDAP', 'INTERNAL', 'AD', name='AuthenticationTypeEnumType'), nullable=True, 
        default=sa.text("'0'")))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'authentication_type')
    # ### end Alembic commands ###
